spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/happytails
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: happytails
    password: 1234

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8095

spring-boot:
  run:
    jvmArguments: -parameters

file:
  dir: /uploads/

# log4jdbc, Mybatis Console Log
logging:
  level:
    com:
      zaxxer:
        hikari: INFO
    javax:
      sql:
        DataSource: OFF
    jdbc:
      audit: OFF
      resultset: OFF
      resultsettable: INFO  #SQL 결과 데이터 Table을 로그로 남긴다.
      sqlonly: OFF     #SQL만 로그로 남긴다.
      sqltiming: INFO    #SQL과 소요시간을 표기한다.
      connection : OFF  # 커넥션 확인가능

kakao:
  api:
    key: 00f8ce605055d2ddbe1b0ee7359a0e6f

portone:
  api:
    key: P2Z4cX3LE4GpectU2WJb9FBwVS3imAnxydy9eqvblMmZLW3KeBqFusZGL9QyGDb3FWNqvQsMovYrWQok
    secret: 자신의_포트원_API_시크릿
  cid: 자신의_포트원_상점_식별자